version: "3.8"

networks:
  monitoring_stack:
    driver: bridge

services:
  flask-app:
    container_name: flask-metrics-logger
    build:
      context: .
      dockerfile: Dockerfile
    image: sayantan2k21/flask-metrics-logger:v1
    ports:
      - "5000:5000"
    networks:
      - monitoring_stack
    environment:
      - PORT=5000
    restart: unless-stopped
