version: "3.8"

networks:
  monitoring_stack:
    driver: bridge

services:
  flask-app:
    container_name: flask-metrics-logger
    build:
      context: .
      dockerfile: Dockerfile
    image: sayantan2k21/flask-metrics-logger:v1
    command: ["./wait-for-it.sh", "prometheus-server:9090", "--",
              "./wait-for-it.sh", "loki-server:3100", "--",
              "./wait-for-it.sh", "blackbox-exporter:9115", "--",
              "python", "app.py"]
    ports:
      - "5000:5000"
    networks:
      - monitoring_stack
    environment:
      - PORT=5000
    restart: unless-stopped
