version: "3.8"

networks:
  monitoring-project-01_microservice_monitoring_stack:
    external: true

services:
  alertmanager:
    container_name: alertmanager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring-project-01_microservice_monitoring_stack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://alertmanager:9093/-/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s