version: "3.8"

networks:
  monitoring-project-01_microservice_monitoring_stack:
    external: true

services:
  prom-server:
    container_name: prometheus-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 9090:9090
    networks:
      - monitoring-project-01_microservice_monitoring_stack
    volumes: 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    restart: unless-stopped
